Python | Plotting Fibonacci spiral fractal using Turtle



 **What is Fractal Geometry?**  
Fractal geometry is a special form of graphical representation of mathematical
functions or set of numbers generated by a mathematical function. It is a
recursive, detailed and infinitely self-similar set of mathematics. These
geometrical representations exhibit **“Unfolding Symmetry”**. Unfolding
symmetry is the property of geometrical structures to retain a self-similar
pattern at infinitesimally small scale.

We know Fibonacci Series follows a recursive relation **f(n) = f(n-1) +
f(n-2)** , where n is the nth term in the series. Again f(0) = 0, f(1) = 1

 ** _Approach of plotting Fibonacci Fractal_**

Each number in the series represent the length of the sides of a square. The
square of side length 0 does not exist. So we start from square of side length
1. The next square is also of side length 1.

  * We first construct the two squares of dimension 1 side by side as shown in the image below.
  * Then taking the joint length of the two squares we construct a third square below the two squares of dimension 1. Now the square is of the dimension 2
  * Again taking the 2 squares of dimension 1, 2 respectively we construct the fourth square of dimension 3
  * Although we continued this process for a small number of iterations but this process continues till infinity.

![](https://media.geeksforgeeks.org/wp-content/uploads/Fibo-Fractal-1-1.png)

